config/routes.rb
Rails.application.routes.draw do

    get 'carts/' => 'carts#show'
    post 'carts/' => 'carts#show'
    
    resources :order_items
    root "products#index"
    
    get '/' => 'product#index'

  resources :products

  get 'charges/index'

  get 'charges/' => 'charges#new'
  get 'charges/new' => 'charges#new'
  get 'charges/create' => 'charges#create'

  post 'charges' => 'charges#create'

  devise_for :users

  

  

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items
  has_attached_file :image, :styles => { :huge => "500x500>", :large => "400x400>", :medium => "300x300>", :small => "200x200>", :tiny => "100x100>" }, :defualt_url => "/images/:style/cool.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/  

  default_scope { where(active: true) }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
   #modified
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
    @carts = current_order.order_items.new
  end
  def new
  	@product = Product.new
  end
  def create
  	@product = Product.new(params[:id])
  	if @product.save
  		redirect_to products_path
  		flash[:notice] = "Product created!"
  	else
  		flash[:alert] = "Product was not created. Please see what went wrong."
  	end
  end
  def show
    @product = Product.find(params[:id])
  end
  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:notice] = "product deleted!"
    else
      flash[:alert] = "There was a problem deleting the product."
    end
    redirect_to products_path
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, :html => {:multipart => true } do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%#= f.label :quantity %><br>
    <%#= f.number_field :quantity %>
  </div>
  <div class="field">
    <%#= f.label :admin_id %><br>
    <%#= f.number_field :admin_id %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
 </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product_row.html.erb
<!-- Content -->
<div id="content">
    <!-- Case -->
    <div class="case">
            <h3>newest
            </h3>
            <!-- Row -->
            <div class="row">      
                <div class="ul">
                  <% @products.each do |product| %>
                    <%= form_for order_item do |f| %>
                    <div class="li">               
                        <a href="#" class="product" title="Product 1">                 
                            <%= image_tag product.image.url(:small) %>
                            <span class="order model">
                                <%= product.name %>
                            </span>
                            <span class="order index-description">
                                <%= product.description %>
                                <span class="number">
                                    <!-- 1111 -->
                                </span>
                            </span>
                            <span class="order">
                               <span class="price">
                                  <!--  <span class="dollar">
                                        $
                                    </span>-->
                                    <%= number_to_currency product.price %>
                                    <!--<span class="sub-text">
                                        .99 
                                    </span>-->
                                </span>
                                <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
                                <span class="buy-text">
                                    <%= f.hidden_field :product_id, value: product.id %>
                                    <%= f.submit "Add to Carts", url: 'http://localhost:3000/carts', class: "btn btn-primary" %>
                               </span>
                        </a>
                    </div>
                    <% end %>
                  <% end %>  
                </div>
                <div class="cl">&nbsp;</div>            
            </div>
            <!-- End Row -->
    </div>
    <!-- End Case -->
</div>
<!-- End Content -->

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<!-- Main -->
<div id="main">
    <!-- Shell -->
    <div class="shell">
        <!-- Header -->
        <div id="header">
            <h1>
                <a href="#" class="notext" title="Shabbos Fish">
                    Shabbos Fish
                </a>
            </h1>

            <div class="cl">&nbsp;</div>
        </div>
        <!-- End Header -->
        <!-- Slider -->
        <div id="main-slider">
            <div id="slider-holder">
                <ul><%# @products.each do |product| %>
                    <%#= image_tag product.slideimage.url(:large) %>
                    <%# end %>
                    <!--  <img src="/images/fish-dorado.jpg"> -->
                    <li style="background-color: #fff;">
                        <img src="/images/fish-dorado.jpg">
                        <div class="cnt">
                            <h4>
                                Enjoy our delecious Fish
                            </h4>
                            <h2>
                                5% off online purchases
                            </h2>
                            <p>
                                Fished stright from the sea.
                            </p>
                            <span class="price">
                                <span class="dollar">
                                    $
                                </span>
                                1599
                                <span class="sub-text">
                                    .99
                                </span>
                            </span>
                            <a href="#" class="btn notext" title="Order Now">
                                Order Now
                            </a>
                            <div class="cl">&nbsp;</div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <!-- End Slider -->

<%# @products.each do |product| %>
<%= render "product_row", product: @product, order_item: @order_item %>
<%# end %>

    </div>
    <!-- End Shell -->
</div>
<!-- End Main -->

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="product-wrapper">
	<p class="name-show-wrap">
	  <strong><!-- Name: --></strong>
	  <span class="name-show-wrap-span">
	  <%= @product.name %>
	  </span>
	</p>
	                                    
	<p class="image-show-wrap">
	  <%= image_tag @product.image.url(:huge) %>
	</p>

	<p class="price-show-wrap">
	  <strong>Price:</strong>
	  <%= @product.price %>
	</p>

	<p class="description-show-wrap">
	  <strong><!-- Description: --></strong>
	  <%= @product.description %>
	</p>

<!-- 	<p class="quantity-show-wrap">
	  <strong>Quantity:</strong>
	  <%#= @product.quantity %>
	</p> -->

	<%= link_to 'Back', products_path %>

	<%#= link_to 'New Order(Checkout)', new_order_path %>
<% form_for @product do |f| %>

<%= f.hidden_field :product_id, :value => @product.id %> 
<%= f.submit 'Add to Carts' %>
<% end %>
    
    
	<% if can? :destroy, @product %>
	<%= link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' } %>
	<% end %>
	<% if can? :edit, @product %>
	<%= link_to 'Edit', edit_product_path(@product) %>
	<% end %>	
    <% if can? :create, @product %>
	<%= link_to 'Create', new_product_path %>
	<% end %>
</div>