config/routes.rb
Rails.application.routes.draw do

    get 'carts/' => 'carts#show'
    post 'carts/' => 'carts#show'
    
    resources :order_items
    root "products#index"
    
    get '/' => 'product#index'

  resources :products

  get 'charges/index'

  get 'charges/' => 'charges#new'
  get 'charges/new' => 'charges#new'
  get 'charges/create' => 'charges#create'

  post 'charges' => 'charges#create'

  devise_for :users

  

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.super_admin? # Admin user
      can :manage, :all
    elsif user.admin? # Admin user
      can :manage, :all
    else # Non-admin user
      can :read, :all
    end
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    
    # belongs_to :user

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

    # validates :user, presence: true

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
  belongs_to :user

  #himmmmmm
  belongs_to :charges



  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end

  attr_accessor :stripe_card_token

  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  rescue Stripe::InvalidRequestError => e
    logger.error "Stripe error while creating customer: #{e.message}"
    errors.add :base, "There was a problem with your credit card."
    false
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
  # validates :user, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items
  has_attached_file :image, :styles => { :huge => "500x500>", :large => "400x400>", :medium => "300x300>", :small => "200x200>", :tiny => "100x100>" }, :defualt_url => "/images/:style/cool.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/  

  default_scope { where(active: true) }
end

app/models/product_order.rb
class ProductOrder < ActiveRecord::Base
	belongs_to :product
	belongs_to :order
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         # belongs_to :admin
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	
  def show
    @order_items = current_order.order_items
    # @products = Product.find(params[:id])
  end
    def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
    # redirect_if_success("/carts") if @order.destroy
  end
  def checkout
    redirect_to charges_controller_create_url
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def index
	end
	def new 
	end
	def create
		
		# Set your secret key: remember to change this to your live secret key in production
		# See your keys here https://dashboard.stripe.com/account
		Stripe.api_key = "sk_test_pwbtG5aDcpDzZyHUJLzyxVAu"

		# Get the credit card details submitted by the form
		stripe_card_token = params[:stripeToken]

		# # Create a Customer
		# customer = Stripe::Customer.create(
		#   :card  => params[:stripeToken],
		#   :email => params[:stripeEmail]
		# )

		# Charge the Customer instead of the card
		Stripe::Charge.create(
			:card  => params[:stripeToken],
		    # :email => params[:stripeEmail],
		    :amount => 1000, # incents
		    :currency => "usd",
		    # :customer => customer.id
		)		
		rescue Stripe::CardError => e
           flash[:alert] = "e.message"
           redirect_to charges_path

		# # Save the customer ID in your database so you can use it later
		# save_stripe_customer_id(User.find(params[:user]), customer.id)

		# # Later...
		# customer_id = get_stripe_customer_id(user)

		# Stripe::Charge.create(
		#   :amount   => 1500, # $15.00 this time
		#   :currency => "usd",
		#   :customer => customer_id
		# )
	end
	def edit 
	end
	def update
	end
	def destroy
	end
# # Set your secret key: remember to change this to your live secret key in production
# # See your keys here https://dashboard.stripe.com/account
# Stripe.api_key = "sk_test_pwbtG5aDcpDzZyHUJLzyxVAu"

# # Get the credit card details submitted by the form
# token = params[:stripeToken]

# # Create a Customer
# customer = Stripe::Customer.create(
#   :card => token,
#   :description => "payinguser@example.com"
# )

# # Charge the Customer instead of the card
# Stripe::Charge.create(
#     :amount => 1000, # incents
#     :currency => "usd",
#     :customer => customer.id
# )

# # Save the customer ID in your database so you can use it later
# save_stripe_customer_id(user, customer.id)

# # Later...
# customer_id = get_stripe_customer_id(user)

# Stripe::Charge.create(
#   :amount   => 1500, # $15.00 this time
#   :currency => "usd",
#   :customer => customer_id
# )
end


	# def new
	# end

	# def create
	#   # Amount is in in cents
	#   # if current_user

	#   @amount = 500

	# 	customer = Stripe::Customer.create(
	# 	  :email => 'example@stripe.com',
	# 	  :card  => params[:stripeToken]
	# 	)


	#   charge = Stripe::Charge.create(
	#     :customer    => customer.id,
	#     :amount      => @amount,
	#     :description => 'Rails Stripe customer',
	#     :currency    => 'usd'
	#   )

	# rescue Stripe::CardError => e
	#   flash[:error] = e.message
	#   redirect_to charges_path
	# end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	# render 'top'
  	# render 'bottom'
  	# def create_order
  	# 	@product = Product.find(params[:id])
  	# 	if product.save 
  	# 		#@order = Order.create(params[:id])
  	# 		#if @order.save
  	# 		redirect_to @checkout
  	# 	end
  	# end
  	# def checkout

  	# end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
   #modified
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
    @carts = current_order.order_items.new
  end
  def new
  	@product = Product.new
  end
  def create
  	@product = Product.new(params[:id])
  	if @product.save
  		redirect_to products_path
  		flash[:notice] = "Product created!"
  	else
  		flash[:alert] = "Product was not created. Please see what went wrong."
  	end
  end
  def show
    @product = Product.find(params[:id])
  end
  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:notice] = "product deleted!"
    else
      flash[:alert] = "There was a problem deleting the product."
    end
    redirect_to products_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_carts_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Carts ( #{number_to_currency current_order.subtotal} )", carts_path, class: "btn btn-link" %>

app/views/layouts/_footer.html.erb
    <!-- Footer -->
    <div id="footer">
        <!-- Shell -->
        <div class="shell">
            <!-- Cols -->
            <div class="cols">
                <ul>
                    <li class="col">
                        <h4>About Shabbos Fish</h4>
                        <p>Quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. <a href="#" title="Duis autem">Duis autem</a> vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu</p>
                        <a href="#" class="more-link" title="Read More">Read More >></a>
                    </li>
                    <li class="col social">
                        <h4>get social</h4>
                        <ul>
                            <li><a href="#" class="fb-link" title="Facebook">facebook</a></li>
                            <li><a href="#" class="twitter-link" title="Twitter">twitter</a></li>
                         <!--    <li><a href="#" class="behance-link" title="Behance">behance</a></li> -->
                            <li><a href="#" class="blogger-link" title="Blogger">blogger</a></li>
                            <!-- <li><a href="#" class="digg-link" title="Digg">digg</a></li> -->
                        </ul>
                    </li>
                    <li class="col partners">
                        <h4>Recipies</h4>
                        <ul>
                            <li><a href="#" title="Lorem ipsum dolor">Lorem ipsum dolor</a></li>
                            <li><a href="#" title="Cras eu lorem id mauris">Cras eu lorem id mauris</a></li>
                            <li><a href="#" title="Proin et velit ut libero">Proin et velit ut libero</a></li>
                            <li><a href="#" title="Velit esse molestie consequat">Velit esse molestie consequat</a></li>
                            <li><a href="#" title="Vel illum dolore eu">Vel illum dolore eu</a></li>
                        </ul>
                    </li>
                    <li class="col contact">
                        <h4>Emails</h4>
                        <p>Sign up for weekly specials</p>
                        <form action="" method="post">
                            <div class="field-wrapper">
                                <input type="text" class="field" placeholder="Name" />
                            </div>
                            <div class="field-wrapper">
                                <input type="text" class="field" placeholder="Email" />
                            </div>
                            <input type="submit" value="Submit" class="submit-btn" title="Submit" />
                            <div class="cl">&nbsp;</div>
                        </form>
                    </li>
                </ul>
                <div class="cl">&nbsp;</div>
            </div>
            <!-- End Cols -->

           <!--  <a href="#" class="logo" title="Shopper Friend"><img src="css/images/footer-logo.png" alt="Shopper Friend" /></a>
            <div class="cl">&nbsp;</div> -->
        </div>
        <!-- End Shell -->
    </div>
    <!-- End Footer -->

app/views/layouts/_topnav.html.erb
<div class="top-nav">
    <ul>
        <li><%= link_to('Home', products_path) %></li>
        <% if current_user %>
        <li>
            <%= current_user.email %>
        </li> 
        <% end %>
        <% if user_signed_in? %>
        <li>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
        </li>
        <% else %>
        <li>
            <%= link_to('Login', new_user_session_path)  %>  
        </li>
        <li>
            <%= link_to "Sign up", new_user_registration_path %>
        </li>        
        <% end %>
        <li class="nobg"><a href="#" class="bag" title="My Bag"><%= render 'layouts/carts_text' %></a></li>
    </ul>
</div>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
<head>
  <title>Project8withcart2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


   


    <!-- Wrapper -->
    <div id="wrapper">
        <!-- Header -->
        <div id="top">
            <!-- Shell -->
            <div class="shell">

                <%= render 'layouts/topnav' %>

                <div class="cl">&nbsp;</div>
            </div>
            <!-- End Shell -->
        </div>
        <!-- End Top -->
        
        <% if notice || alert %>
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
        <% end %> 

<%= yield %>
     
        <div id="footer-push" class="cl">&nbsp;</div>
    </div>
    <!-- End Wrapper -->
    
    <%= render 'layouts/footer' %>


    <%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
<%= tag :meta, :name => "stripe-key", :content => 'pk_KcSyS2qPWdT5SdrwkQg0vNSyhZgqP' %>
</body>
</html>
  

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
	<head>
	</head>
	<body>
		<%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
<%= tag :meta, :name => "stripe-key", :content => 'pk_KcSyS2qPWdT5SdrwkQg0vNSyhZgqP' %>
	  <%= yield %>
	</body>
</html>